image: golang:1.15

pipelines:
  default:
    - parallel:
      - step:
          name: Test and Build
          script:
            - go mod vendor
            - go mod tidy
            - go test -v -cover
            - mkdir build
            - go build -o build/gostations github.com/gmgauthier/gostations
      - step:
          name: Lint code
          image: golangci/golangci-lint:v1.31.0
          script:
            - golangci-lint run -v
